apiVersion: v1
kind: ConfigMap
metadata:
  name: identity-config
  namespace: bingeo-app
data:
  NODE_ENV: "development"
  PORT: "3001"
  OTEL_SERVICE_NAME: "identity-service"
  OTEL_EXPORTER_OTLP_ENDPOINT: "http://otel-collector.bingeo-obs:4317"
  LOKI_URL: "http://loki.bingeo-obs:3100"
