apiVersion: apps/v1
kind: Deployment
metadata:
  name: identity-service
  namespace: bingeo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: identity-service
      type: api
  template:
    metadata:
      labels:
        app: identity-service
        type: api
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "3001"
    spec:
      containers:
        - name: identity
          image: bingeo/identity-service
          ports:
            - containerPort: 3001
          envFrom:
            - configMapRef:
                name: identity-config
            - secretRef:
                name: identity-secrets
          livenessProbe:
            httpGet:
              path: /health
              port: 3001
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: 3001
            initialDelaySeconds: 30
            periodSeconds: 5
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
            requests:
              memory: "256Mi"
              cpu: "250m"
